site_name: SDD
site_description: Supervised and Unsupervised Learning section of the Algorithms in Machine Learning class at ISAE-Supaero
site_url: https://supaerodatascience.github.io/machine-learning/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/machine-learning/main/src/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/machine-learning/main/src/favicon.ico'
  features:
    - navigation.sections

repo_name: SupaeroDataScience/machine-learning
repo_url: https://github.com/SupaeroDataScience/machine-learning


nav:
- Home: https://supaerodatascience.github.io/index.html

- Classes:
  - Fundamentals of Decision Making: https://supaerodatascience.github.io/310/index.html
  
  - Machine Learning: 
    - Overview: https://supaerodatascience.github.io/aml.html
    - Machine Learning: 
      - Introduction: index.md
      - A geometrical approach to ML: geometric.md
      - A probabilistic approach to ML: probabilistic.md
      - Commitee-based methods: commitee.md
      - Explainability in ML: xai.md
    - Deep Larning: https://supaerodatascience.github.io/deep-learning/
    - Reinforcement learning: https://supaerodatascience.github.io/reinforcement-learning/

  - Data Engineering: https://supaerodatascience.github.io/DE/

  - Applied Data Science: https://supaerodatascience.github.io/313/index.html

  - Seminars: https://supaerodatascience.github.io/seminars.html

- Resources:
  - For current students: https://supaerodatascience.github.io/infostudents.html
  - For prospective students: https://supaerodatascience.github.io/students.html
  - For partners: https://supaerodatascience.github.io/partners.html
  - Contact: https://supaerodatascience.github.io/contact.html



markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences
- pymdownx.snippets:
    check_paths: true
    auto_append: []
- pymdownx.arithmatex:
    generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
